name: Cypress Tests

on:
  - push
  - pull_request

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
          ref: ${{ github.event.pull_request.head.sha }}
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          browser: chrome
          record: true
          start: npm run serve:vue
          wait-on: http://localhost:8080/
          wait-on-timeout: 120
        env:
          CYPRESS_baseUrl: http://localhost:8080/