name: Pre-Production Deployments

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ (github.event_name == 'pull_request' && 'Testing') || (github.event_name == 'push' && 'Staging') }}
    steps:
      - uses: actions/checkout@v2
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_ENVIRONMENT_CI_TOKEN }}"
          channelId: live
          projectId: "${{ secrets.FIREBASE_PROJECT_ID }}"